#!/bin/sh -e

mount -o ro,bind ../toybox-x86_64 ./bin/toybox
mount -o ro,bind $(which busybox) ./bin/busybox
mount -o ro,bind /tmp ./tmp
mount -t proc proc ./proc
mount -o ro -t tmpfs tmpfs .hako # Hide directory's content

# Enable loopback networking
ip link set lo up
